name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest
        pip install -r requirements.txt
        pip install .
    - name: Check code style with Black
      run: |
        black -l 80 --check map_machine tests
    - name: Lint with Flake8
      run: |
        flake8 --max-line-length=80 --ignore=E203,W503
    - name: Test with pytest
      run: |
        pytest -v
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest
        pip install -r requirements.txt
        pip install .
    - name: Check code style with Black
      run: |
        black -l 80 --check map_machine setup.py tests
    - name: Lint with Flake8
      run: |
        flake8 --max-line-length=80 --ignore=E203,W503
    - name: Test render
      run: |
        map-machine render -b 10.000,20.000,10.001,20.001 --cache tests/data
